### PR TITLE
Extend Dockerfile to use plain multi stage build

### PR DESCRIPTION
**Pull request by apinnecke**
During the development of #436 I set up a docker hub repo with automatic building of the docker image to test the setup in place. To achieve that I changed the Dockerfile to use multi stage builds to be build-system agnostic and compile the go binary in place. I'm not sure whether that's useful for you so I opened this PR to check back. 👋

### CODE REVIEW

**Comment by abstractj** [comment]
@apinnecke @robbiemcmichael could you please file a Jira (https://issues.jboss.org/browse/KEYCLOAK-8856), add the affected version and steps to reproduce the issue? It helps us to plan/prioritize the next releases.

**Comment by apinnecke** [comment]
@abstractj this is a PR, not an issue. And you obviously didn‘t even read the PR?!

**Comment by abstractj** [comment]
@apinnecke JIRA is used for feature requests too. Please, read https://github.com/keycloak/keycloak-gatekeeper/blob/master/README.md#help-and-documentation

**Comment by apinnecke** [comment]
This PR is not a feature request 😂

**Comment by abstractj** [comment]
@apinnecke no problem. If it's not a feature request, an enhancement or a bug. I appreciate the time you took submitting it, but I believe it does not fit into this repository. For Docker images, please send PRs to https://github.com/jboss-dockerfiles/keycloak/tree/master/gatekeeper. Also make sure to file a Jira ;)

**Pull request closed without merging**
