### PR TITLE
[KEYCLOAK-12100] Add ISO8601 Time Encoder for logs timestamps.

### PR DESCRIPTION
**Pull request by Madankapoor**
Hi
This is a PR for including the formating of the timestamp in logs for human readability and security audits. This is my first PR, with a plausible simple approach. Please guide me further on the approach.

### CODE REVIEW

**Comment by Madankapoor** [comment]
@abstractj  Hi could you please give me some feedback on this pull request?

**Comment by abstractj** [comment]
@Madankapoor thanks for submitting this. Even though I appreciate the change, I think we need to work on a design proposal to provide a proper encoder for logging, if we're going to add more flags to Gatekeeper, I'd rather have something like https://github.com/openshift/ocp-release-operator-sdk/blob/a497e0f5d565dfe8be3f9025c0a85b38dc1085b8/doc/user/logging.md#default-zap-logger.

Let me ask what others think on the dev mailing list and will get back to you this week.

**Comment by Madankapoor** [comment]
Hi, @abstractj Thanks for the feedback.   It makes sense to have something like https://github.com/openshift/ocp-release-operator-sdk/blob/a497e0f5d565dfe8be3f9025c0a85b38dc1085b8/doc/user/logging.md#default-zap-logger which would give more flexibility and extendability.   Let's discuss a more elaborate approach and I am also willing to volunteer to implement it after discussion.

**Comment by Madankapoor** [comment]
Closing PR as suggested by @abstractj  and waiting for a better design proposal. With reference to
conversation in 
- https://issues.redhat.com/browse/KEYCLOAK-12100
- https://groups.google.com/d/msg/keycloak-dev/fahLWU5NlEQ/ZbGHJK7vBAAJ

**Pull request closed without merging**
